spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_catalog?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 890311
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl